## Alıştırma 1
Köşegenin hemen altında 1,2,3,4 değerlerine sahip 5x5'lik bir matris oluşturun

![figure](https://i0.wp.com/arrayjson.com/wp-content/uploads/2020/06/numpy-diagonal-offset-0-1-2-1-2.jpg?resize=454%2C309&ssl=1)

In [3]:
import numpy as np
M = np.diag(np.arange(1,4),k=2)
print(M)

[[0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]
 [0 0 0 0 0]]


## Alıştırma 2
Kartezyen koordinatları temsil eden rastgele bir 10x2 matrisi, kutupsal koordinatlara dönüştürün.
![figure](https://www.grc.nasa.gov/WWW/K-12/airplane/Images/coords.jpg)

In [9]:
import numpy as np
z = np.random.random((10,2))
print('KOORDİNAT LİSTESİ')
print('--------------------------')
print(z)
print('-----------------------------')
x,y = z[:,0], z[:,1]
print('X KOORDİNATLARI LİSTESİ')
print(x)
print('--------------------------')
print('Y KOORDİNATLARI LİSTESİ')
print(y)
print('--------------------------')
r = np.sqrt(x**2+y**2)
print('KUTUPSAL YARIÇAP (r)')
print(r)
print('--------------------------')
theta = np.arctan2(y,x)
print('KUTUPSAL AÇI (Theta)')
print(theta)


KOORDİNAT LİSTESİ
--------------------------
[[0.54607308 0.68182604]
 [0.9268241  0.66535192]
 [0.03327053 0.88821712]
 [0.39071424 0.38287904]
 [0.5231282  0.02628663]
 [0.63521378 0.58946375]
 [0.24598394 0.32146678]
 [0.3954546  0.5888944 ]
 [0.1820441  0.59963926]
 [0.12754436 0.22212132]]
-----------------------------
X KOORDİNATLARI LİSTESİ
[0.54607308 0.9268241  0.03327053 0.39071424 0.5231282  0.63521378
 0.24598394 0.3954546  0.1820441  0.12754436]
--------------------------
Y KOORDİNATLARI LİSTESİ
[0.68182604 0.66535192 0.88821712 0.38287904 0.02628663 0.58946375
 0.32146678 0.5888944  0.59963926 0.22212132]
--------------------------
KUTUPSAL YARIÇAP (r)
[0.87354596 1.14091897 0.88884002 0.54704111 0.52378822 0.86658182
 0.40478265 0.70935249 0.62666362 0.2561356 ]
--------------------------
KUTUPSAL AÇI (Theta)
[0.89550809 0.62262789 1.53335618 0.77527018 0.05020669 0.74805873
 0.91764276 0.97944098 1.2760498  1.04955571]


## Alıştırma 3
Boyutu 10 olan rastgele bir vektörün en büyük elemanını 1'e, en küçük elemanını 0'a eşitleyiniz.

In [12]:
import numpy as np
Z5 = np.random.random(10)
print(Z5)

print('EN BÜYÜK ELEMANIN 1\'E EŞİTLENMESİ')
Z5[np.argmax(Z5)] = 1
print(Z5)
print('------------------------------------')
print('EN KÜÇÜK ELEMANIN 0\'A EŞİTLENMESİ')
Z5[np.argmin(Z5)] = 0
print(Z5)

[0.85904274 0.86387284 0.19037369 0.04166168 0.82140963 0.22042315
 0.746958   0.90014191 0.84686671 0.33021595]
EN BÜYÜK ELEMANIN 1'E EŞİTLENMESİ
[0.85904274 0.86387284 0.19037369 0.04166168 0.82140963 0.22042315
 0.746958   1.         0.84686671 0.33021595]
------------------------------------
EN KÜÇÜK ELEMANIN 0'A EŞİTLENMESİ
[0.85904274 0.86387284 0.19037369 0.         0.82140963 0.22042315
 0.746958   1.         0.84686671 0.33021595]
