**T.C. Mersin Üniversitesi Mühendislik Fakültesi – Harita Mühendisliği Bölümü**

2024-2025 Akademik Yılı Güz Dönemi

1603006 Programlama Dersi – Ara Sınavı – 11 Kasım 2024

Dosyanızı **İsim_Soyisim_Numara_AraSinav.ipynb** ismiyle kaydediniz ve caniban@mersin.edu.tr adresine sınav süresi dolmadan e-posta gönderiniz. E-postanızın konu kısmına da **İsim_Soyisim_Numara_AraSinav** yazınız. Buluttan bağlantı vermeyiniz. Doğrudan .ipynb dosyanızı Colab'tan masaüstüne indirip, e-posta eki olarak gönderiniz.

Süre 75 dakikadır. Üretken yapay zeka kullanımı yasaktır. 

Doç. Dr. Muzaffer Can İBAN

**Soru 1:** 0'dan 8'e kadar rakamlardan oluşan 3x3'lük bir matris oluşturunuz (10 puan)

In [1]:
import numpy as np
matris = np.arange(9).reshape(3, 3)
print("3x3'lük Matris:")
print(matris)

3x3'lük Matris:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Soru 2:** Kullanıcıdan $x$, $y$ ve $z$ değerlerini input olarak istedikten sonra aşağıdaki formülün çözümünü yapınız ve sonucu ekrana yazdırınız. 
$$(x + y) \cdot z - \frac{x}{y}$$

(10 puan)

In [2]:
# Kullanıcıdan x, y ve z değerlerini al
x = float(input("x değerini giriniz: "))
y = float(input("y değerini giriniz: "))
z = float(input("z değerini giriniz: "))

# Formülü hesapla
sonuc = (x + y) * z - (x / y)

# Sonucu ekrana yazdır
print("Sonuç:", sonuc)

x değerini giriniz: 6
y değerini giriniz: 4
z değerini giriniz: 3
Sonuç: 28.5


**Soru 3:** Kullanıcıdan bir sayı girmesini isteyip bunu ondalık sayı, tam sayı ve karmaşık sayı türlerine sırayla dönüştüren bir Python programı yazınız. (15 puan)

In [3]:
# Kullanıcıdan bir sayı girmesini iste
sayi = input("Bir sayı giriniz: ")

# Sayıyı farklı veri türlerine dönüştürme
tam_sayi = int(float(sayi))  # Float olarak alıp int'e çevirerek tam sayı yapıyoruz
ondalik_sayi = float(sayi)
karmaşık_sayi = complex(sayi)

# Sonuçları ekrana yazdır
print("Tam sayı:", tam_sayi)
print("Ondalık sayı:", ondalik_sayi)
print("Karmaşık sayı:", karmaşık_sayi)

Bir sayı giriniz: 12.6
Tam sayı: 12
Ondalık sayı: 12.6
Karmaşık sayı: (12.6+0j)


**Soru 4:** Bir dikdörtgen prizma şeklindeki tankın uzunluğu 8 metre, genişliği 6 metre ve yüksekliği 3 metredir. Tankın %75’i doludur. Saatte 20 metreküp su tahliye edebilen bir pompa ile tank tamamen boşaltılacaktır. Bu işlemin ne kadar süreceğini hesaplayan bir program yazınız (25 puan).

In [4]:
# Tankın hacmini hesaplayalım
uzunluk = 8  # metre
genislik = 6  # metre
yukseklik = 3  # metre
toplam_hacim = uzunluk * genislik * yukseklik  # metreküp

# Doluluk oranı
dolu_hacim = toplam_hacim * 0.75  # metreküp

# Pompa kapasitesi
pompa_kapasitesi = 20  # metreküp/saat

# Gerekli zamanı hesaplayalım
gereken_sure = dolu_hacim / pompa_kapasitesi
print("Tankı tamamen boşaltmak için gereken süre:", gereken_sure, "saat")

Tankı tamamen boşaltmak için gereken süre: 5.4 saat


**Soru 5:** Aşağıdaki süpermarket zincirlerini içeren bir liste oluşturun:

`"metro", "tesco", "walmart", "kmart", "carrefour"`


Listeye `"lidl"` ve `"aldi"` süpermarketlerini append yöntemi ile ekleyin ve tüm marketleri alfabetik sıraya göre ekrana yazdırın. (10 puan)

In [5]:
# Süpermarket zincirlerini içeren liste
supermarkets = ["metro", "tesco", "walmart", "kmart", "carrefour"]

# Listeye "lidl" ve "aldi" marketlerini ekleme
supermarkets.append("lidl")
supermarkets.append("aldi")

# Listeyi alfabetik sıraya göre sıralama
supermarkets.sort()

# Sonucu ekrana yazdırma
print("Alfabetik sıraya göre süpermarket zincirleri:", supermarkets)


Alfabetik sıraya göre süpermarket zincirleri: ['aldi', 'carrefour', 'kmart', 'lidl', 'metro', 'tesco', 'walmart']


**Soru 6:** Aşağıdaki tabloda, bazı gerçek değerler ve bu değerler için hesaplanan tahmini değerler verilmiştir. Gerçek Değer ve Hesaplanan Değer arasındaki kök karesel ortalama hatayı NumPy ile hesaplayacak bir Python programı yazınız (30 puan).

| Gerçek Değer | Hesaplanan Değer |
|--------------|------------------|
| 100000       | 98521           |
| 200000       | 204572          |
| 300000       | 299637          |
| 400000       | 412781          |
| 500000       | 503469          |
| 600000       | 598601          |


$
KKOH = \sqrt{\frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2}
$

Burada:

$y_i $ gerçek değerleri,

$ \hat{y}_i $ hesaplanan değerleri,

$ n $ ise toplam veri sayısını temsil eder.

In [6]:
import numpy as np

# Gerçek değerler ve hesaplanan değerler
gercek_degerler = np.array([100000, 200000, 300000, 400000, 500000, 600000])
hesaplanan_degerler = np.array([98521, 204572, 299637, 412781, 503469, 598601])

# KKOH formülünü uygulayalım
# (Gerçek Değerler - Hesaplanan Değerler) karelerinin ortalamasını alıp, sonra karekökünü alıyoruz.
kareler_farki = (gercek_degerler - hesaplanan_degerler) ** 2
ortalama_kare_farki = np.mean(kareler_farki)
kkoh = np.sqrt(ortalama_kare_farki)

# Sonucu yazdıralım
print(f"Kök Karesel Ortalama Hata (KKOH): {kkoh}")


Kök Karesel Ortalama Hata (KKOH): 5781.688291494103
