**T.C. Mersin Üniversitesi Mühendislik Fakültesi – Harita Mühendisliği Bölümü**

2021-2022 Akademik Yılı Güz Dönemi

Programlama – Ara Sınavı – 17 Kasım 2021 Çarşamba

Dr. Öğr. Üyesi Muzaffer Can İBAN




**Soru 1:** 0'dan 8'e kadar rakamlardan oluşan 3x3'lük bir matris oluşturunuz (5 puan)

In [ ]:
import numpy as np
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Soru 2:**

a) Rastgele sayılardan oluşan 10x10 boyutlarında bir matris oluşturunuz (5 puan).

b) Bu matristeki maksimum, minimum ve ortalama değerleri hesaplayınız (5 puan).

In [ ]:
K = np.random.random((10,10))
K_min = np.min(K)
K_max = np.max(K)
K_ort = np.mean(K)
print(K_min, K_max, K_ort)

0.01666345489676313 0.9938192225341658 0.49012601733686817


**Soru 3:**  Aşağıdaki programda gerçekleştirilmek istenen amacı ve sonucu sözlü olarak ifade ediniz (5 puan). 

In [ ]:
nl=[]
for x in range(1600, 2100):
    if (x%7==0) and (x%5==0):
        nl.append(str(x))
print (','.join(nl))

1610,1645,1680,1715,1750,1785,1820,1855,1890,1925,1960,1995,2030,2065


Cevabınızı buraya giriniz: *Programın içerisindeki for döngüsü ile 1600 ile 2100 araındaki tam sayılar seçilmiştir. Seçilen bu tam sayılar, for döngüsü içindeki if ifadesi ile belirli bir şarta tabi tutulmuştur. Bu sayılar hem 7'ye hem de 5'e kalansız bölünüyorsa, bu bu sayılar string formatına çevrilerek tek tek n1 boş listesine eklenmektedir. Eklenen her sayı, liste içinde virgülle ayrılmıştır.*

**Soru 4:** Aşağıda bulunan listedeki tüm isimleri, `"Merhaba! [isim]"` formatında ekrana veriniz (`for` döngüsünü kullanınız) (10 puan). 

In [ ]:
liste = ["Erdem", "Fatih", "Ceyda", "Sevim"]

In [ ]:
for i in liste:
  print("Merhaba! " + i)

Merhaba! Erdem
Merhaba! Fatih
Merhaba! Ceyda
Merhaba! Sevim


**Soru 5:** Aşağıdaki `liste1` de bulunan sayıların karelerini `liste2` içine aktarıp ekrana veren programı tamamlayınız (`for` döngüsü ve `.append` yöntemini kullanınız) (10 puan).

In [1]:
liste1 = [3,4,5,6,7]
liste2 = []
# Cevabınızı buraya giriniz.
for i in liste1:
  liste2.append(i**2)

print(liste2)

[9, 16, 25, 36, 49]


**Soru 6:** Kullanıcının girdiği bir tam sayının, 3'e bölünüp bölünmediğini kullanıcıya gösteren bir program yazınız (10 puan). 

In [ ]:
sayi = int(input("Bir sayı giriniz: "))

if sayi%3==0:
  print("Sayı 3'e bölünebilmektedir")
else:
  print("Sayı 3'e bölünememektedir")

Bir sayı giriniz: 27
Sayı 3'e bölünebilmektedir


**Soru 7:** Kullanıcının girdiği bir metin ifadesinin ilk harfinin `a` harfi olup olmadığını kullanıcıya sunan bir program yazınız. Kullanıcının girdiği metnin büyük harfle başlaması olasılığına karşı gerekli önlemi alınız (10 puan). 

In [ ]:
ifade= str(input("Metin ifadesi giriniz: "))
if ifade[0].lower()=="a":
  print("İfade a harfi ile başlamaktadır")
else:
  print("İfade a harfi ile başlamamaktadır")

Metin ifadesi giriniz: ARDAHAN
İfade a harfi ile başlamaktadır


**Soru 8:** Toplu taşınmaz değerleme çalışmalarında, taşınmazın kestirilen değeri ile piyasadaki gerçek değerlerinin tutarlılığını ölçmek için çeşitli ölçütler kullanılır. Bu ölçütlerden biri de **Dağıtım Katsayısı** olarak adlandırılan **COD** ölçütüdür. COD ölçütünün formülü aşağıdaki gibidir.

$COD = \frac{\frac{\sum_{i=1}^{n}\left | R_{i}-\tilde{R} \right |}{n}}{\tilde{R}}*100$

Burada $R_{i}$ her bir taşınmazın kestirilen değeri ile piyasadaki gerçek değerinin oranını vermektedir. $\tilde{R}$ ise bu $R_{i}$ değerlerinin medyanıdır. ${n}$ ise veri setinde kullanılan toplam taşınmaz sayısıdır.

Diğer bir ölçüt ise ** Kök Karesel Ortalama Hatadır (KKOH)** ve aşağıdaki formülle ifade edilir.

$KKOH = \sqrt{\frac{\sum_{i=1}^{n}(y_{i}-\hat{y}_{i})^{2}}{n}} $

Burada $y_{i}$ taşınmazın gerçek değerini, $\hat{y}_{i}$ ise kestirilen değerini temsil etmektedir.

Buna göre aşağıda verilen tablodaki verileri kullanarak, bu taşınmazlar için COD ve KKOH ölçütlerini hesaplayınız (40 puan).

| Taşınmaz No     | Gerçek Değeri           | Kestirilen Değer                                                |
|--------------|----------------|--------------------------------------------------------|
| 01   | 870000       | 875250                             |
|02   | 1100000        |1105000                               |
| 03   | 956000         | 957200|
| 04    | 296000  | 300000                              |
| 05   | 645000        | 649000           |






In [ ]:
kestirim = np.array([875250,1105000, 957200, 300000, 649000])
gercek = np.array([870000, 1100000, 956000, 296000 , 645000 ])

R=kestirim/gercek
R_median=np.median(R)
COD=np.mean((np.abs(R-R_median))/R_median)*100
print(COD)
KKOH= np.sqrt(np.mean((gercek-kestirim)**2))
print(KKOH)

0.2766183360232063
4147.348550580238
